// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLHeJt8G2aX83JHKjSuzUzZcM5TzR8eI',
    appId: '1:924271561405:web:cadc8b21b9bdf66a0605d4',
    messagingSenderId: '924271561405',
    projectId: 'llm-app-93388',
    authDomain: 'llm-app-93388.firebaseapp.com',
    storageBucket: 'llm-app-93388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABdok3tScGMC8UIP9fx4nQyGv9eh28O-I',
    appId: '1:924271561405:android:335f708d57ce98fd0605d4',
    messagingSenderId: '924271561405',
    projectId: 'llm-app-93388',
    storageBucket: 'llm-app-93388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWVfN8MD8PItFfMzZcNGHFRTcGA5Wsu4',
    appId: '1:924271561405:ios:baa53b76068316ba0605d4',
    messagingSenderId: '924271561405',
    projectId: 'llm-app-93388',
    storageBucket: 'llm-app-93388.firebasestorage.app',
    iosBundleId: 'com.example.llmVideoShopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWVfN8MD8PItFfMzZcNGHFRTcGA5Wsu4',
    appId: '1:924271561405:ios:baa53b76068316ba0605d4',
    messagingSenderId: '924271561405',
    projectId: 'llm-app-93388',
    storageBucket: 'llm-app-93388.firebasestorage.app',
    iosBundleId: 'com.example.llmVideoShopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpLHeJt8G2aX83JHKjSuzUzZcM5TzR8eI',
    appId: '1:924271561405:web:0e5e857d633ab0d40605d4',
    messagingSenderId: '924271561405',
    projectId: 'llm-app-93388',
    authDomain: 'llm-app-93388.firebaseapp.com',
    storageBucket: 'llm-app-93388.firebasestorage.app',
  );

}